package ru.vpavlova.tm.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-05-11T12:58:04.088+03:00
 * Generated source version: 3.4.2
 *
 */
@WebService(targetNamespace = "http://endpoint.tm.vpavlova.ru/", name = "AdminEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface AdminEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.tm.vpavlova.ru/AdminEndpoint/unlockUserByLoginRequest", output = "http://endpoint.tm.vpavlova.ru/AdminEndpoint/unlockUserByLoginResponse")
    @RequestWrapper(localName = "unlockUserByLogin", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.UnlockUserByLogin")
    @ResponseWrapper(localName = "unlockUserByLoginResponse", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.UnlockUserByLoginResponse")
    public void unlockUserByLogin(

        @WebParam(name = "session", targetNamespace = "")
        ru.vpavlova.tm.endpoint.Session session,
        @WebParam(name = "login", targetNamespace = "")
        java.lang.String login
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.vpavlova.ru/AdminEndpoint/addAllUsersRequest", output = "http://endpoint.tm.vpavlova.ru/AdminEndpoint/addAllUsersResponse")
    @RequestWrapper(localName = "addAllUsers", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.AddAllUsers")
    @ResponseWrapper(localName = "addAllUsersResponse", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.AddAllUsersResponse")
    public void addAllUsers(

        @WebParam(name = "session", targetNamespace = "")
        ru.vpavlova.tm.endpoint.Session session,
        @WebParam(name = "users", targetNamespace = "")
        java.util.List<ru.vpavlova.tm.endpoint.User> users
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.vpavlova.ru/AdminEndpoint/addUserRequest", output = "http://endpoint.tm.vpavlova.ru/AdminEndpoint/addUserResponse")
    @RequestWrapper(localName = "addUser", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.AddUserResponse")
    public void addUser(

        @WebParam(name = "session", targetNamespace = "")
        ru.vpavlova.tm.endpoint.Session session,
        @WebParam(name = "user", targetNamespace = "")
        ru.vpavlova.tm.endpoint.User user
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.vpavlova.ru/AdminEndpoint/updateUserRequest", output = "http://endpoint.tm.vpavlova.ru/AdminEndpoint/updateUserResponse")
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.UpdateUserResponse")
    public void updateUser(

        @WebParam(name = "session", targetNamespace = "")
        ru.vpavlova.tm.endpoint.Session session,
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId,
        @WebParam(name = "firstName", targetNamespace = "")
        java.lang.String firstName,
        @WebParam(name = "lastName", targetNamespace = "")
        java.lang.String lastName,
        @WebParam(name = "middleName", targetNamespace = "")
        java.lang.String middleName
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.vpavlova.ru/AdminEndpoint/lockUserByLoginRequest", output = "http://endpoint.tm.vpavlova.ru/AdminEndpoint/lockUserByLoginResponse")
    @RequestWrapper(localName = "lockUserByLogin", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.LockUserByLogin")
    @ResponseWrapper(localName = "lockUserByLoginResponse", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.LockUserByLoginResponse")
    public void lockUserByLogin(

        @WebParam(name = "session", targetNamespace = "")
        ru.vpavlova.tm.endpoint.Session session,
        @WebParam(name = "login", targetNamespace = "")
        java.lang.String login
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.vpavlova.ru/AdminEndpoint/removeOneByLoginRequest", output = "http://endpoint.tm.vpavlova.ru/AdminEndpoint/removeOneByLoginResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://endpoint.tm.vpavlova.ru/AdminEndpoint/removeOneByLogin/Fault/Exception")})
    @RequestWrapper(localName = "removeOneByLogin", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.RemoveOneByLogin")
    @ResponseWrapper(localName = "removeOneByLoginResponse", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.RemoveOneByLoginResponse")
    public void removeOneByLogin(

        @WebParam(name = "session", targetNamespace = "")
        ru.vpavlova.tm.endpoint.Session session,
        @WebParam(name = "login", targetNamespace = "")
        java.lang.String login
    ) throws Exception_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.vpavlova.ru/AdminEndpoint/setUserPasswordRequest", output = "http://endpoint.tm.vpavlova.ru/AdminEndpoint/setUserPasswordResponse")
    @RequestWrapper(localName = "setUserPassword", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.SetUserPassword")
    @ResponseWrapper(localName = "setUserPasswordResponse", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.SetUserPasswordResponse")
    public void setUserPassword(

        @WebParam(name = "session", targetNamespace = "")
        ru.vpavlova.tm.endpoint.Session session,
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.vpavlova.ru/AdminEndpoint/removeUserRequest", output = "http://endpoint.tm.vpavlova.ru/AdminEndpoint/removeUserResponse")
    @RequestWrapper(localName = "removeUser", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.RemoveUser")
    @ResponseWrapper(localName = "removeUserResponse", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.RemoveUserResponse")
    public void removeUser(

        @WebParam(name = "session", targetNamespace = "")
        ru.vpavlova.tm.endpoint.Session session,
        @WebParam(name = "user", targetNamespace = "")
        ru.vpavlova.tm.endpoint.User user
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.vpavlova.ru/AdminEndpoint/findAllUsersRequest", output = "http://endpoint.tm.vpavlova.ru/AdminEndpoint/findAllUsersResponse")
    @RequestWrapper(localName = "findAllUsers", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.FindAllUsers")
    @ResponseWrapper(localName = "findAllUsersResponse", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.FindAllUsersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.vpavlova.tm.endpoint.User> findAllUsers(

        @WebParam(name = "session", targetNamespace = "")
        ru.vpavlova.tm.endpoint.Session session
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.vpavlova.ru/AdminEndpoint/createUserWithEmailRequest", output = "http://endpoint.tm.vpavlova.ru/AdminEndpoint/createUserWithEmailResponse")
    @RequestWrapper(localName = "createUserWithEmail", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.CreateUserWithEmail")
    @ResponseWrapper(localName = "createUserWithEmailResponse", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.CreateUserWithEmailResponse")
    public void createUserWithEmail(

        @WebParam(name = "session", targetNamespace = "")
        ru.vpavlova.tm.endpoint.Session session,
        @WebParam(name = "login", targetNamespace = "")
        java.lang.String login,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "email", targetNamespace = "")
        java.lang.String email
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.vpavlova.ru/AdminEndpoint/createUserRequest", output = "http://endpoint.tm.vpavlova.ru/AdminEndpoint/createUserResponse")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.CreateUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.vpavlova.tm.endpoint.User createUser(

        @WebParam(name = "session", targetNamespace = "")
        ru.vpavlova.tm.endpoint.Session session,
        @WebParam(name = "login", targetNamespace = "")
        java.lang.String login,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.vpavlova.ru/AdminEndpoint/clearUsersRequest", output = "http://endpoint.tm.vpavlova.ru/AdminEndpoint/clearUsersResponse")
    @RequestWrapper(localName = "clearUsers", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.ClearUsers")
    @ResponseWrapper(localName = "clearUsersResponse", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.ClearUsersResponse")
    public void clearUsers(

        @WebParam(name = "session", targetNamespace = "")
        ru.vpavlova.tm.endpoint.Session session
    );
}
