
package ru.vpavlova.tm.endpoint;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-05-11T12:58:04.084+03:00
 * Generated source version: 3.4.2
 */

@WebFault(name = "Exception", targetNamespace = "http://endpoint.tm.vpavlova.ru/")
public class Exception_Exception extends java.lang.Exception {

    private ru.vpavlova.tm.endpoint.Exception faultInfo;

    public Exception_Exception() {
        super();
    }

    public Exception_Exception(String message) {
        super(message);
    }

    public Exception_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, ru.vpavlova.tm.endpoint.Exception exception) {
        super(message);
        this.faultInfo = exception;
    }

    public Exception_Exception(String message, ru.vpavlova.tm.endpoint.Exception exception, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = exception;
    }

    public ru.vpavlova.tm.endpoint.Exception getFaultInfo() {
        return this.faultInfo;
    }
}
