package ru.vpavlova.tm.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-05-06T10:21:51.252+03:00
 * Generated source version: 3.4.2
 *
 */
@WebService(targetNamespace = "http://endpoint.tm.vpavlova.ru/", name = "ProjectEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface ProjectEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.tm.vpavlova.ru/ProjectEndpoint/findProjectByIdRequest", output = "http://endpoint.tm.vpavlova.ru/ProjectEndpoint/findProjectByIdResponse")
    @RequestWrapper(localName = "findProjectById", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.FindProjectById")
    @ResponseWrapper(localName = "findProjectByIdResponse", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.FindProjectByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.vpavlova.tm.endpoint.Project findProjectById(

        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id,
        @WebParam(name = "session", targetNamespace = "")
        ru.vpavlova.tm.endpoint.Session session
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.vpavlova.ru/ProjectEndpoint/clearRequest", output = "http://endpoint.tm.vpavlova.ru/ProjectEndpoint/clearResponse")
    @RequestWrapper(localName = "clear", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.Clear")
    @ResponseWrapper(localName = "clearResponse", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.ClearResponse")
    public void clear(

        @WebParam(name = "session", targetNamespace = "")
        ru.vpavlova.tm.endpoint.Session session
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.vpavlova.ru/ProjectEndpoint/removeProjectByIdRequest", output = "http://endpoint.tm.vpavlova.ru/ProjectEndpoint/removeProjectByIdResponse")
    @RequestWrapper(localName = "removeProjectById", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.RemoveProjectById")
    @ResponseWrapper(localName = "removeProjectByIdResponse", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.RemoveProjectByIdResponse")
    public void removeProjectById(

        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id,
        @WebParam(name = "session", targetNamespace = "")
        ru.vpavlova.tm.endpoint.Session session
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.vpavlova.ru/ProjectEndpoint/findAllProjectsRequest", output = "http://endpoint.tm.vpavlova.ru/ProjectEndpoint/findAllProjectsResponse")
    @RequestWrapper(localName = "findAllProjects", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.FindAllProjects")
    @ResponseWrapper(localName = "findAllProjectsResponse", targetNamespace = "http://endpoint.tm.vpavlova.ru/", className = "ru.vpavlova.tm.endpoint.FindAllProjectsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.vpavlova.tm.endpoint.Project> findAllProjects(

        @WebParam(name = "session", targetNamespace = "")
        ru.vpavlova.tm.endpoint.Session session
    );
}
